name: edutec_hub
description: "A new Flutter project for course booking with BLoC, GoRouter, and multi-language support."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  go_router: ^13.0.1
  intl: ^0.19.0
  easy_localization: ^3.0.5
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  lottie: ^3.1.2
  dio: ^5.7.0
  flutter_stripe: ^11.1.0
  package_info_plus: ^8.0.2
  open_filex: ^4.5.0
  url_launcher: ^6.3.0
  equatable: ^2.0.5
  external_path: ^2.0.1
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  curved_navigation_bar: ^1.0.6
  flutter_screenutil: ^5.9.3
  table_calendar: ^3.1.2
  shared_preferences: ^2.3.2
  retrofit: ^4.4.0
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  image_picker: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  flutter_flavorizr: ^2.2.1
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0



flutter:
  uses-material-design: true
  # generate: true

  assets:
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - assets/introduction_animation/
    - assets/translations/
    - assets/animations/
    - assets/images/school/ 

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
